import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CalendarDays, ChevronRight, Clock3, Home, Map, Menu, Navigation, Settings, Store, Wifi, X } from 'lucide-react';
import { branding } from './config/branding';
import { pharmacies, settings as initialSettings, visits as initialVisits } from './data/demo';
import type { Pharmacy, PlannedVisit } from './types';
import './styles.css';

type Page = 'Heute' | 'Woche' | 'Runde' | 'Apotheken' | 'Mehr';
const navItems: [Page, React.ComponentType<{size?: number}>][] = [['Heute', Home], ['Woche', CalendarDays], ['Runde', Map], ['Apotheken', Store], ['Mehr', Settings]];
const mapsUrl = (p: Pharmacy) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.street}, ${p.postalCode} ${p.city}`)}`;

function App() {
  const [page, setPage] = useState<Page>('Heute');
  const [week, setWeek] = useState(2);
  const [visits, setVisits] = useState<PlannedVisit[]>(initialVisits);
  const [notice, setNotice] = useState<string | null>(null);
  const [traffic, setTraffic] = useState(true);
  const [selectedPharmacy, setSelectedPharmacy] = useState<Pharmacy | null>(null);
  const pharmacy = (id: string) => pharmacies.find(p => p.id === id)!;
  const todayVisits = visits.slice(0, 4);
  const moveDemo = () => { const v = visits.find(x => x.week === 3); if (v) { setVisits(visits.map(x => x.id === v.id ? {...x, week: 2} : x)); setNotice('Apotheke vorgezogen. Gelbe Warnung: Die Kapazität der Zielwoche wurde neu bewertet.'); } };
  return <div className="app"><aside><img src={branding.logo} alt="Engelhard"/><nav>{navItems.map(([label, Icon]) => <button key={label} className={page === label ? 'active' : ''} onClick={() => setPage(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="side-foot"><Wifi size={16}/> Offline-Demo</div></aside><main><header><div className="mobile-brand"><Menu size={22}/><span>{branding.appName}</span></div><div><span className="eyebrow">Montag, 3. August 2026</span><h1>{page}</h1></div><div className="avatar">AJ</div></header>{page === 'Heute' && <Today visits={todayVisits} pharmacy={pharmacy} traffic={traffic} setTraffic={setTraffic} onOpen={setSelectedPharmacy}/>} {page === 'Woche' && <Week week={week} setWeek={setWeek} visits={visits.filter(v => v.week === week)} pharmacy={pharmacy} onMove={moveDemo} notice={notice}/>} {page === 'Runde' && <Cycle/>} {page === 'Apotheken' && <Pharmacies onOpen={setSelectedPharmacy}/>} {page === 'Mehr' && <SettingsPage/>}</main>{selectedPharmacy && <PharmacyModal pharmacy={selectedPharmacy} onClose={() => setSelectedPharmacy(null)}/>}</div>;
}

const Card = ({children, className = ''}: {children: React.ReactNode; className?: string}) => <section className={`card ${className}`}>{children}</section>;
const Pill = ({children, tone = 'neutral'}: {children: React.ReactNode; tone?: string}) => <span className={`pill ${tone}`}>{children}</span>;
const NavigationButton = ({pharmacy}: {pharmacy: Pharmacy}) => <a className="nav-button" href={mapsUrl(pharmacy)} target="_blank" rel="noreferrer"><Navigation size={15}/> Navigation</a>;

function RouteMap({visits, pharmacy, traffic, compact = false}: {visits: PlannedVisit[]; pharmacy: (id: string) => Pharmacy; traffic: boolean; compact?: boolean}) { return <div className={`route-map ${compact ? 'compact' : ''}`}><div className="map-toolbar"><b><Map size={16}/> Tagesroute</b><Pill tone={traffic ? 'traffic' : 'success'}>{traffic ? 'Dichter Verkehr' : 'Normaler Verkehr'}</Pill></div><div className="map-canvas"><div className="map-road road-a"/><div className="map-road road-b"/><div className="map-home"><Home size={14}/></div>{visits.map((v, i) => { const p = pharmacy(v.pharmacyId); return <div className={`map-pin pin-${i + 1}`} key={v.id}><span>{i + 1}</span><label>{p.city}</label></div>; })}<div className="map-legend"><span><i className="legend-line"/> Route</span><span><i className="legend-dot"/> Apotheke</span></div></div><div className="map-summary"><span><b>4</b> Stationen</span><span><Clock3 size={14}/> {traffic ? '1 h 48 min' : '1 h 32 min'} Fahrzeit</span><span className="traffic-copy">{traffic ? '+16 min Verkehrspuffer' : 'Keine Verzögerung'}</span></div></div>; }

function Today({visits, pharmacy, traffic, setTraffic, onOpen}: {visits: PlannedVisit[]; pharmacy: (id: string) => Pharmacy; traffic: boolean; setTraffic: (v: boolean) => void; onOpen: (p: Pharmacy) => void}) { return <><div className="hero"><div><span className="eyebrow">Dein Arbeitstag</span><h2>Guten Morgen, Alex</h2><p>4 Besuche geplant · 5 h 40 min im Einsatz</p></div></div><div className="traffic-toggle"><span><span className="live-dot"/> Verkehrslage berücksichtigt</span><button onClick={() => setTraffic(!traffic)} className={traffic ? 'toggle on' : 'toggle'}><i/></button></div><RouteMap visits={visits} pharmacy={pharmacy} traffic={traffic}/><div className="grid two"><Card><div className="card-title"><h3>Heutige Besuche</h3><Pill tone="success">Gut ausgelastet</Pill></div>{visits.map((v, i) => <div className="visit-row" key={v.id}><div className="time">{['10:00','11:30','13:30','15:00'][i]}</div><div className="visit-info"><b>{pharmacy(v.pharmacyId).name}</b><small>{pharmacy(v.pharmacyId).street}, {pharmacy(v.pharmacyId).city} · {pharmacy(v.pharmacyId).duration} min</small></div><Pill tone={pharmacy(v.pharmacyId).priority.toLowerCase()}>{pharmacy(v.pharmacyId).priority}</Pill><NavigationButton pharmacy={pharmacy(v.pharmacyId)}/><button className="icon-button" title="Details" onClick={() => onOpen(pharmacy(v.pharmacyId))}><ChevronRight size={16}/></button></div>)}</Card><Card className="overnight-card"><span className="eyebrow">Übernachtungshinweis</span><h3>Heute Heimfahrt empfohlen</h3><p>Der heutige Cluster liegt nah genug: ca. 38 Minuten bis zum Heimatstandort.</p></Card></div></>; }

function Week({week, setWeek, visits, pharmacy, onMove, notice}: {week: number; setWeek: (v: number) => void; visits: PlannedVisit[]; pharmacy: (id: string) => Pharmacy; onMove: () => void; notice: string | null}) { const all = useMemo(() => visits.length ? visits : initialVisits.slice((week - 1) * 3, week * 3), [visits, week]); return <><div className="toolbar"><div><span className="eyebrow">Wochenplanung</span><h2>KW {31 + week} · 03.–07. August</h2></div><select value={week} onChange={e => setWeek(+e.target.value)}>{[1,2,3,4,5].map(x => <option key={x} value={x}>KW {31 + x}</option>)}</select></div>{notice && <div className="alert">⚠ {notice}</div>}<RouteMap visits={all} pharmacy={pharmacy} traffic/><Card className="week-calendar"><div className="card-title"><h3>Alle Besuche dieser Woche</h3><Pill tone="success">{all.length} Apotheken</Pill></div>{all.map((v, i) => <div className="week-visit" key={v.id}><b>{['Mo','Di','Mi','Do','Fr'][i % 5]}</b><span>{pharmacy(v.pharmacyId).name}<small>{pharmacy(v.pharmacyId).city} · {pharmacy(v.pharmacyId).duration} min</small></span><Pill tone={pharmacy(v.pharmacyId).priority.toLowerCase()}>{pharmacy(v.pharmacyId).priority}</Pill><NavigationButton pharmacy={pharmacy(v.pharmacyId)}/></div>)}</Card><Card><div className="card-title"><h3>Demo-Aktion</h3><Pill tone="yellow">Aus späterer Woche</Pill></div><p>Apotheke aus KW 33 in diese Woche vorziehen.</p><button className="secondary" onClick={onMove}>Apotheke vorziehen</button></Card></>; }

function Cycle() { return <><div className="toolbar"><div><span className="eyebrow">Verkaufsrunde</span><h2>03.08. – 25.10.2026</h2></div><button className="primary">Gesamtrunde optimieren</button></div><div className="grid stats"><Card><span className="eyebrow">Apotheken</span><h3>25</h3><p>Alle 25 Besuche eingeplant</p></Card><Card><span className="eyebrow">Kapazität</span><h3>5 / Tag</h3><p className="green">Arbeitszeit wird optimal genutzt</p></Card><Card><span className="eyebrow">Gesamtzeit</span><h3>64 h</h3><p>39 h Besuche · 25 h Fahrt</p></Card></div><Card><h3>Kapazitätslogik</h3><p>Die Runde plant die 25 Apotheken auf die verfügbaren Arbeitstage und füllt jeden Tag bis zur maximalen Kapazität. Eine Streckung über zusätzliche Wochen erfolgt nicht.</p></Card></>; }
function Pharmacies({onOpen}: {onOpen: (p: Pharmacy) => void}) { const [q, setQ] = useState(''); const list = pharmacies.filter(p => `${p.name} ${p.city}`.toLowerCase().includes(q.toLowerCase())); return <><div className="toolbar"><div><span className="eyebrow">Stammdaten</span><h2>25 Apotheken</h2></div></div><input className="search" placeholder="Apotheke oder Ort suchen …" value={q} onChange={e => setQ(e.target.value)}/><Card><div className="table">{list.map(p => <div className="pharm-row" key={p.id}><div className="store-icon"><Store size={17}/></div><div><b>{p.name}</b><small>{p.street}, {p.postalCode} {p.city}</small></div><Pill tone={p.priority.toLowerCase()}>Priorität {p.priority}</Pill><NavigationButton pharmacy={p}/><button className="icon-button" onClick={() => onOpen(p)}><ChevronRight size={17}/></button></div>)}</div></Card></>; }
function SettingsPage() { return <Card><h3>Planungseinstellungen</h3><p>Arbeitszeit, Besuchsdauer, Kapazität und Übernachtungsregeln sind für den POC konfigurierbar.</p></Card>; }
function PharmacyModal({pharmacy, onClose}: {pharmacy: Pharmacy; onClose: () => void}) { return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={onClose}><X/></button><span className="eyebrow">Apothekendetails</span><h2>{pharmacy.name}</h2><p>{pharmacy.street}, {pharmacy.postalCode} {pharmacy.city}</p><div className="modal-actions"><NavigationButton pharmacy={pharmacy}/><button className="secondary" onClick={onClose}>Schließen</button></div></div></div>; }

createRoot(document.getElementById('root')!).render(<App/>);
