import { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MapContainer, Marker, Polyline, TileLayer, Tooltip, useMap } from 'react-leaflet';
import L from 'leaflet';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Home, MapPinned, MoonStar, Navigation, Route, Settings2, SlidersHorizontal, Sparkles, Store, TrendingUp } from 'lucide-react';
import { pharmacies, settings as demoSettings } from './data/demo';
import type { Pharmacy, Settings } from './types';
import 'leaflet/dist/leaflet.css';
import './styles.css';

type View = 'dashboard' | 'plan' | 'pharmacies' | 'settings';
type Day = { name: string; date: string; visits: Pharmacy[]; drive: number; distance: number; overnight: boolean };
const home: [number, number] = [50.2024, 8.8057];
const marker = (n: number, active = false) => L.divIcon({ className: 'route-marker-wrap', html: `<div class="route-marker ${active ? 'active' : ''}">${n}</div>`, iconSize: [32, 32], iconAnchor: [16, 16] });

function mapDays(): Day[] {
  const areas = [['Montag', '03. Aug.', pharmacies.filter(p => p.region === 'Rhein-Main Ost')], ['Dienstag', '04. Aug.', pharmacies.filter(p => p.region === 'Rhein-Main Süd')], ['Mittwoch', '05. Aug.', pharmacies.filter(p => p.region === 'Rhein-Main West')]] as const;
  return areas.map(([name, date, list], i) => ({ name, date, visits: list.slice(0, i === 0 ? 4 : 3), drive: i === 0 ? 96 : i === 1 ? 118 : 142, distance: i === 0 ? 74 : i === 1 ? 108 : 126, overnight: i === 2 }));
}

function FitRoute({ points }: { points: [number, number][] }) { const map = useMap(); if (points.length) map.fitBounds(points, { padding: [46, 46], maxZoom: 10 }); return null; }
function TourMap({ day, active = 0 }: { day: Day; active?: number }) {
  const points = [home, ...day.visits.map(p => [p.lat, p.lng] as [number, number]), ...(day.overnight ? [] : [home])];
  return <div className="tour-map"><MapContainer center={home} zoom={9} scrollWheelZoom={false} aria-label="Karte der heutigen Route"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><FitRoute points={points}/><Marker position={home} icon={L.divIcon({ className: 'home-marker-wrap', html: '<div class="home-marker">⌂</div>', iconSize: [32,32], iconAnchor:[16,16] })}><Tooltip>Start: Niederdorfelden</Tooltip></Marker><Polyline positions={points} pathOptions={{ color: '#0067A0', weight: 5, opacity: .86 }}/>{day.visits.map((p, i) => <Marker key={p.id} position={[p.lat, p.lng]} icon={marker(i + 1, i === active)}><Tooltip direction="top" offset={[0,-12]}>{p.name}</Tooltip></Marker>)}</MapContainer><div className="map-overlay"><span><Route size={15}/> {day.distance} km</span><span><Clock3 size={15}/> {Math.floor(day.drive / 60)} h {day.drive % 60} min</span></div></div>;
}

function App() {
  const [view, setView] = useState<View>('dashboard');
  const [settings, setSettings] = useState<Settings>(() => JSON.parse(localStorage.getItem('routeplanner-settings') || JSON.stringify(demoSettings)));
  const [dayIndex, setDayIndex] = useState(0);
  const [optimised, setOptimised] = useState(false);
  const days = useMemo(() => mapDays(), []); const today = days[dayIndex];
  const updateSetting = (key: keyof Settings, value: string | number | boolean) => { const next = { ...settings, [key]: value }; setSettings(next); localStorage.setItem('routeplanner-settings', JSON.stringify(next)); };
  const navigate = (next: View) => setView(next);
  return <div className="shell"><aside className="sidebar"><div className="brand"><img src="/routeplanner/branding/engelhard-logo.svg" alt="Engelhard"/><span>Routeplanner</span></div><nav>{[["dashboard", MapPinned, 'Übersicht'], ['plan', CalendarDays, 'Verkaufsrunde'], ['pharmacies', Store, 'Apotheken'], ['settings', Settings2, 'Einstellungen']].map(([key, Icon, label]) => <button key={key} className={view === key ? 'selected' : ''} onClick={() => navigate(key as View)}><Icon size={19}/>{label}</button>)}</nav><div className="demo-label"><Sparkles size={14}/> POC · synthetische Daten</div></aside><main><header><div><span className="kicker">ENGELHARD AUSSENDIENST</span><h1>{view === 'dashboard' ? 'Deine Tour, klar geplant.' : view === 'plan' ? 'Verkaufsrunde' : view === 'pharmacies' ? 'Apotheken' : 'Planungsregeln'}</h1></div><button className="profile">AJ</button></header>{view === 'dashboard' && <Dashboard day={today} dayIndex={dayIndex} setDayIndex={setDayIndex} onPlan={() => navigate('plan')}/>} {view === 'plan' && <SalesCycle days={days} optimised={optimised} setOptimised={setOptimised}/>} {view === 'pharmacies' && <Pharmacies/>} {view === 'settings' && <Settings settings={settings} update={updateSetting}/>}</main></div>;
}

function Dashboard({ day, dayIndex, setDayIndex, onPlan }: { day: Day; dayIndex: number; setDayIndex: (n: number) => void; onPlan: () => void }) { return <><section className="today-head"><div><span className="kicker">{day.name.toUpperCase()} · {day.date.toUpperCase()} 2026</span><h2>{day.visits.length} Besuche. Eine optimale Route.</h2><p>Rhein-Main Ost · Start und Ende in Niederdorfelden</p></div><div className="day-switch"><button disabled={dayIndex === 0} onClick={() => setDayIndex(dayIndex - 1)}><ChevronLeft/></button><span>Tour {dayIndex + 1}/3</span><button disabled={dayIndex === 2} onClick={() => setDayIndex(dayIndex + 1)}><ChevronRight/></button></div></section><section className="route-stage"><TourMap day={day}/><div className="route-panel"><div className="route-panel-head"><span className="kicker">TAGESPLAN</span><span className="status good">optimal</span></div><h3>Heute im Blick</h3><div className="metric-line"><strong>08:30</strong><span>Abfahrt Niederdorfelden</span></div>{day.visits.map((p,i) => <div className="stop" key={p.id}><div className="stop-number">{i+1}</div><div><b>{p.name}</b><small>{p.city} · {p.duration} Min. Besuch</small></div><button title="Navigation starten" onClick={() => window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.street}, ${p.postalCode} ${p.city}`)}`, '_blank')}><Navigation size={17}/></button></div>)}<div className="metric-line last"><strong>16:18</strong><span>Rückkehr Niederdorfelden</span></div></div></section><section className="insight-grid"><article className="insight primary-insight"><div><span className="kicker">TAGESQUALITÄT</span><h3>Die Route nutzt deinen Tag sinnvoll.</h3><p>4 Besuche, 74 km und ausreichend Zeit für Nachbereitung.</p></div><TrendingUp size={28}/></article><article className="insight"><span className="kicker">FAHRZEIT</span><strong>1 h 36 min</strong><p>davon 18 Minuten Puffer</p></article><article className="insight"><span className="kicker">ÜBERNACHTUNG</span><strong><Home size={18}/> Heimfahrt</strong><p>38 Min. bis Niederdorfelden</p></article></section><section className="next"><div><div><span className="kicker">NÄCHSTER SCHRITT</span><h3>Die gesamte 12-Wochen-Runde prüfen</h3><p>Kapazitäten, Cluster und Übernachtungen werden auf einen Blick sichtbar.</p></div><button className="button" onClick={onPlan}>Runde öffnen <ChevronRight size={17}/></button></div></section></> }
function SalesCycle({ days, optimised, setOptimised }: { days: Day[]; optimised: boolean; setOptimised: (v:boolean)=>void }) { return <><section className="cycle-head"><div><span className="kicker">03. AUG. – 25. OKT. 2026 · 12 WOCHEN</span><h2>25 Apotheken. Ein verlässlicher Rhythmus.</h2></div><button className="button" onClick={() => setOptimised(true)}><Sparkles size={17}/> {optimised ? 'Runde aktualisiert' : 'Runde optimieren'}</button></section>{optimised && <div className="success-banner">Deine Runde wurde neu ausbalanciert: 48 Minuten weniger Fahrzeit und ein Übernachtungshinweis statt einer unnötigen Heimfahrt.</div>}<section className="cycle-stats"><div><span>GEPLANTE BESUCHE</span><strong>25 <small>/ 25</small></strong><i style={{width:'100%'}}/></div><div><span>GESAMTFAHRZEIT</span><strong>24 h <small>12 min</small></strong><p className="positive">− 48 min nach Optimierung</p></div><div><span>ÜBERNACHTUNGEN</span><strong>2</strong><p>empfohlen, nicht verpflichtend</p></div></section><section className="week-board"><div className="board-head"><div><span className="kicker">WOCHE 1</span><h3>03. – 07. August</h3></div><span className="status good">4 von 4 Tagen ausbalanciert</span></div>{days.map(d=><article className="tour-row" key={d.name}><div className="tour-date"><strong>{d.name}</strong><span>{d.date}</span></div><div className="tour-route"><span>{d.visits.map(p=>p.city).filter((v,i,a)=>a.indexOf(v)===i).join(' · ')}</span><small>{d.visits.length} Besuche · {d.distance} km · {Math.floor(d.drive/60)} h {d.drive%60} min Fahrt</small></div><div className="overnight">{d.overnight ? <><MoonStar size={17}/><span>Übernachtung empfohlen</span></> : <><Home size={17}/><span>Heimfahrt sinnvoll</span></>}</div><button className="row-action">Details <ChevronRight size={16}/></button></article>)}</section></> }
function Pharmacies(){ const [query,setQuery]=useState(''); const list=pharmacies.filter(p=>`${p.name} ${p.city}`.toLowerCase().includes(query.toLowerCase())); return <><section className="intro"><span className="kicker">DEMO-STAMMDATEN</span><h2>25 Apotheken für den POC</h2><p>Keine Echtkundendaten. Alle Adressen und Namen sind synthetisch.</p></section><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Apotheke oder Ort suchen"/>
<section className="pharmacy-list">{list.map(p=><article key={p.id}><div className={`priority priority-${p.priority}`}>{p.priority}</div><div><b>{p.name}</b><small>{p.street} · {p.postalCode} {p.city}</small></div><span>{p.region}</span><strong>{p.duration} Min.</strong></article>)}</section></> }
function Settings({settings,update}:{settings:Settings;update:(k:keyof Settings,v:string|number|boolean)=>void}){return <><section className="intro"><span className="kicker">DEINE PLANUNGSREGELN</span><h2>Eine Runde, die zu deinem Alltag passt.</h2><p>Änderungen werden lokal gespeichert und bei der nächsten Planung berücksichtigt.</p></section><section className="settings-card"><div><MapPinned/><div><b>Startpunkt</b><small>Wo deine Verkaufsrunde beginnt</small></div><input value={settings.homeBase} onChange={e=>update('homeBase',e.target.value)}/></div><div><Clock3/><div><b>Standard-Besuchsdauer</b><small>Wird für flexible Termine verwendet</small></div><select value={settings.defaultVisitDuration} onChange={e=>update('defaultVisitDuration',+e.target.value)}><option value="30">30 Minuten</option><option value="45">45 Minuten</option><option value="60">60 Minuten</option></select></div><div><SlidersHorizontal/><div><b>Max. Besuche pro Tag</b><small>Schützt vor unrealistischen Tagesplänen</small></div><select value={settings.maxVisitsPerDay} onChange={e=>update('maxVisitsPerDay',+e.target.value)}><option value="4">4 Besuche</option><option value="5">5 Besuche</option><option value="6">6 Besuche</option></select></div><div><MoonStar/><div><b>Übernachtungen empfehlen</b><small>Wenn Heimfahrt den Arbeitstag deutlich verlängert</small></div><button className={settings.overnightEnabled?'toggle on':'toggle'} onClick={()=>update('overnightEnabled',!settings.overnightEnabled)}><i/></button></div></section></>}
createRoot(document.getElementById('root')!).render(<App/>);
